name: CI

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install pnpm manually
        run: npm install -g pnpm

      - name: Print PATH and pnpm location
        run: |
          echo "PATH is: $PATH"
          which pnpm
          pnpm --version

      - name: Install deps and run unit tests
        run: |
          pnpm install
          pnpm run test

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install pnpm manually
        run: npm install -g pnpm

      - name: Print PATH and pnpm location
        run: |
          echo "PATH is: $PATH"
          which pnpm
          pnpm --version

      - name: Install deps and run E2E tests
        run: |
          pnpm install
          npx playwright install --with-deps
          pnpm run test:e2e
